Added Infix to Postfix Convertor using stack cpp
ritikbanger/Hacktoberfest2022-DSA pull request #18
Opened 2022-10-02 12:18 UTC by chiragchandnani10

2022-10-02 14:22 UTC, ritikbanger requested changes

2022-10-02 16:05 UTC, chiragchandnani10 commented on 30. CPP Programs/Infix_To_Postfix.cpp
> +            //     res+=st.top();
> Please remove the commented code if it is not useful

Done @ritikbanger Please mark it hacktoberfest-accepted! Thanks a lot!

2022-10-02 16:27 UTC, chiragchandnani10 commented on 30. CPP Programs/Infix_To_Postfix.cpp
> +            //     res+=st.top();
@ritikbanger I have ran the code in my PC and its working now. Could you please merge this PR and mark it hacktoberfest-accepted? Thank you so much and god bless you.

2022-10-02 16:27 UTC, chiragchandnani10 commented
@ritikbanger I have ran the code in my PC and its working now. Could you please merge this PR and mark it hacktoberfest-accepted? Thank you so much and god bless you. (I am sorry to write so many times, this is my first open source experience)

2022-10-03 05:11 UTC, ritikbanger commented
Don't forget to star this repository and share on your social media about this repo for hacktoberfest. Thank you for the contribution.

2022-10-03 05:11 UTC, merged