88_Merge Sorted Array
ritikbanger/Hacktoberfest2022-DSA pull request #53
Opened 2022-10-04 05:35 UTC by djharshit

2022-10-05 06:53 UTC, djharshit commented
This PR has been excluded, it is saying this repository did not follow the hacktoberfest guidelines. Why ?

2022-10-08 06:16 UTC, ritikbanger commented
> This PR has been excluded, it is saying this repository did not follow the hacktoberfest guidelines. Why ?

Because nobody is solving issues, everyone copy paste code for the t-shirt.

2022-10-08 06:17 UTC, ritikbanger requested changes

2022-10-08 06:17 UTC, ritikbanger commented on 04. Arrays/26_Remove Duplicates from Sorted Array.py
> +class Solution:
Change file name, it should not contain any spaces, refer to readme.

2022-10-08 06:17 UTC, ritikbanger commented on 04. Arrays/88_Merge Sorted Array.py
> +class Solution:
Change file name, it should not contain any spaces, refer to readme.

2023-02-26 05:07 UTC, closed without merging